icons_format = "{icon}"

[theme]
theme = "native"

[icons]
icons = "awesome4"

[[block]]
block = "focused_window"
[block.format]
full = " $marks $title.str(max_w:35) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "cpu"
format = "$icon $utilization"
format_alt = "$icon $frequency"

[[block]]
block = "temperature"
format = "CPU $average|"
chip = "k10temp-*"
inputs = ["Tccd1"]
scale = "celsius"
interval = 5

[[block]]
block = "temperature"
format = "GPU $average|"
chip = "amdgpu-*"
inputs = ["edge"]
scale = "celsius"
interval = 5

[[block]]
block = "temperature"
format = "NVMe $average|"
chip = "nvme-*"
inputs = ["Composite"]
scale = "celsius"
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $available.eng(w:2) "
[[block.click]]
button = "right"
update = true

[[block]]
block = "memory"
format = "$icon $mem_total_used_percents.eng(w:2) "
format_alt = "$icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
headphones_indicator = true
format = "$icon {$volume.eng(w:2) |}"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = "$icon $timestamp.datetime(f:'%F %I:%M') "

