return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "cpp",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "json",
      "lua",
      "make",
      "markdown_inline",
      "python",
      "rust",
      "sql",
      "swift",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
      "zig",
    },
  },
}
