[colors]
"diff removed token" = { underline = false }
"diff added token" = { underline = false }

[fix.tools.ruff-format]
command = ["uvx", "ruff", "format", "--stdin-filename=$path"]
patterns = ["glob:'**/*.py'"]
enabled = false

[fix.tools.ruff-isort]
command = ["uvx", "ruff", "check", "--quiet", "--select=I", "--fix", "--stdin-filename=$path"]
patterns = ["glob:'**/*.py'", "glob:'**/*.pyi'"]
enabled = false

[git]
colocate = true
private-commits = "description(glob:'wip:*')"

[snapshot]
auto-track = "none()"

[templates]
log = "my_log_oneline"
git_push_bookmark = '"chore/" ++ change_id.short()'

[template-aliases]
# Highlight unique prefix and show at least 5 characters
'format_short_id(id)' = 'id.shortest(5)'

# Just the shortest possible unique prefix
#'format_short_id(id)' = 'id.shortest()'
description_placeholder = 'label("description placeholder", "()")'

my_log_oneline = 'my_log_oneline(self)'
'my_log_oneline(commit)' = '''
if(commit.root(),
  format_root_commit(commit),
  label(
    separate(" ",
      if(commit.current_working_copy(), "working_copy"),
      if(commit.immutable(), "immutable", "mutable"),
      if(commit.conflict(), "conflicted"),
    ),
    concat(
      "\t",
      separate(" ",
        format_short_change_id_with_change_offset(commit),
        if(
          commit.author().email(),
          pad_end(8, truncate_end(8, commit.author().email().local(), "…")),
          email_placeholder
        ),
        format_short_commit_id(commit.commit_id()),
        pad_end(
          10,
          separate(" ",
            if(commit.empty(), label("empty", "(∅)")),
            commit.bookmarks(),
            commit.tags(),
            commit.working_copies(),
            if(commit.contained_in('first_parent(@)'), label("git_head", "HEAD")),
            if(commit.conflict(), label("conflict", "conflict")),
          ),
          label("elided", ".")
        ),
        if(
          commit.description(),
          truncate_end(72, commit.description().first_line(), "…"),
          description_placeholder,
        ),
      ) ++ "\n",
    )
  )
)
'''

changelog = 'concat("\t", truncate_end(9, commit_id), " ", tags, "- ", if(description, description.first_line(), description_placeholder))'

[ui]
default-command = "log"
# diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
editor = "nvim"
diff-editor = ":builtin"

[user]
name = "Peter Grayson"
email = "pete@jpgrayson.net"
