[colors]
"diff removed token" = { underline = false }
"diff added token" = { underline = false }

[git]
private-commits = "description(glob:'wip:*')"
push-bookmark-prefix = "chore/"

[snapshot]
auto-track = "none()"

[template-aliases]
# Highlight unique prefix and show at least 5 characters
'format_short_id(id)' = 'id.shortest(5)'

# Just the shortest possible unique prefix
#'format_short_id(id)' = 'id.shortest()'
description_placeholder = 'label("description placeholder", "()")'

my_log_oneline = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      "\t",
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        if(author.email(), author.email().local(), email_placeholder),
        format_short_commit_id(commit_id),
        pad_end(
          10,
          separate(" ",
            if(empty, label("empty", "(∅)")),
            bookmarks,
            tags,
            working_copies,
            if(git_head, label("git_head", "HEAD")),
            if(conflict, label("conflict", "conflict")),
          ),
          label("elided", ".")
        ),
        if(
          description,
          description.first_line(),
          description_placeholder,
        ),
      ) ++ "\n",
    ),
  )
)
'''

changelog = 'concat("\t", truncate_end(9, commit_id), " ", tags, "- ", if(description, description.first_line(), description_placeholder))'

[ui]
default-command = ["log", "-T", "my_log_oneline"]
# diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
editor = "nvim"

[user]
name = "Peter Grayson"
email = "pete@jpgrayson.net"
